name: reservasi_rawat_jalan_mobile
description: Aplikasi Reservasi Rawat Jalan berbasis Mobile

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

isar_version: &isar_version 3.1.0+1

dependencies:
  flutter:
    sdk: flutter


  bloc: ^8.1.2
  cached_network_image: ^3.3.1
  connectivity_plus: ^6.0.3
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  device_preview: ^1.1.0
  dio: ^5.4.0
  easy_localization: ^3.0.3
  equatable: ^2.0.5
  firebase_core: ^2.30.1
  firebase_messaging: ^14.9.3
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.1.0
  flutter_gen: ^5.4.0
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.9
  get_it: ^7.6.7
  go_router: ^13.1.0
  image_picker: ^1.0.7
  intl: ^0.18.1
  isar: *isar_version
  isar_flutter_libs: *isar_version
  json_annotation: ^4.8.1
  lottie: ^3.1.0
  path_provider: ^2.1.2
  package_info_plus: ^8.0.0
  pinput: ^4.0.0
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.1.0
  syncfusion_flutter_datepicker: ^25.1.41

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  flutter_gen_runner: ^5.4.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1
  isar_generator: *isar_version
  json_serializable: ^6.7.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/launcher/android_logo.png"
  min_sdk_android: 16

flutter_gen:
  output: lib/core/gen/
  line_length: 80

  integrations:
    flutter_svg: true
    rive: true
    lottie: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/raw/
    - assets/fonts/
    - assets/icons/
    - assets/langs/
    - .env

  fonts:
    - family: Sf-Pro
      fonts:
        - asset: assets/fonts/Sf-Pro/SF-Pro-Display-Ultralight.otf
          weight: 100
        - asset: assets/fonts/Sf-Pro/Sf-Pro-Display-UltralightItalic.otf
          style: italic
          weight: 100
        - asset: assets/fonts/Sf-Pro/Sf-Pro-Display-Thin.otf
          weight: 200
        - asset: assets/fonts/Sf-Pro/Sf-Pro-Display-ThinItalic.otf
          style: italic
          weight: 200
        - asset: assets/fonts/Sf-Pro/SF-Pro-Display-Light.otf
          weight: 300
        - asset: assets/fonts/Sf-Pro/SF-Pro-Display-LightItalic.otf
          style: italic
          weight: 300
        - asset: assets/fonts/Sf-Pro/SF-Pro-Display-Regular.otf
          weight: 400
        - asset: assets/fonts/Sf-Pro/SF-Pro-Display-RegularItalic.otf
          style: italic
          weight: 400
        - asset: assets/fonts/Sf-Pro/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: assets/fonts/Sf-Pro/SF-Pro-Display-MediumItalic.otf
          style: italic
          weight: 500
        - asset: assets/fonts/Sf-Pro/SF-Pro-Display-Semibold.otf
          weight: 600
        - asset: assets/fonts/Sf-Pro/SF-Pro-Display-SemiboldItalic.otf
          style: italic
          weight: 600
        - asset: assets/fonts/Sf-Pro/SF-Pro-Display-Bold.otf
          weight: 700
        - asset: assets/fonts/Sf-Pro/Sf-Pro-Display-BoldItalic.otf
          style: italic
          weight: 700
        - asset: assets/fonts/Sf-Pro/Sf-Pro-Display-Black.otf
          weight: 800
        - asset: assets/fonts/Sf-Pro/Sf-Pro-Display-BlackItalic.otf
          style: italic
          weight: 800
        - asset: assets/fonts/Sf-Pro/Sf-Pro-Display-Heavy.otf
          weight: 900
        - asset: assets/fonts/Sf-Pro/Sf-Pro-Display-HeavyItalic.otf
          style: italic
          weight: 900