name: reservasi_rawat_jalan_mobile
description: Aplikasi Reservasi Rawat Jalan berbasis Mobile

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  bloc: ^8.1.2
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  device_preview: ^1.1.0
  dio: ^5.4.0
  easy_localization: ^3.0.3
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.1.0
  flutter_svg: ^2.0.9
  get_it: ^7.6.7
  go_router: ^13.1.0
  image_picker: ^1.0.7
  intl: ^0.18.1
  json_annotation: ^4.8.1
  lottie: ^3.0.0
  package_info_plus: ^5.0.1
  shimmer: ^3.0.0
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  flutter_gen_runner: ^5.4.0
  flutter_lints: ^3.0.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/raw/
    - assets/fonts/
    - assets/icons/
    - assets/langs/
    - .env

  fonts:
    - family: Sf-Pro
      fonts:
        - asset: assets/fonts/Sf-Pro/SF-Pro-Display-Ultralight.otf
          weight: 100
        - asset: assets/fonts/Sf-Pro/Sf-Pro-Display-UltralightItalic.otf
          style: italic
          weight: 100
        - asset: assets/fonts/Sf-Pro/Sf-Pro-Display-Thin.otf
          weight: 200
        - asset: assets/fonts/Sf-Pro/Sf-Pro-Display-ThinItalic.otf
          style: italic
          weight: 200
        - asset: assets/fonts/Sf-Pro/SF-Pro-Display-Light.otf
          weight: 300
        - asset: assets/fonts/Sf-Pro/SF-Pro-Display-LightItalic.otf
          style: italic
          weight: 300
        - asset: assets/fonts/Sf-Pro/SF-Pro-Display-Regular.otf
          weight: 400
        - asset: assets/fonts/Sf-Pro/SF-Pro-Display-RegularItalic.otf
          style: italic
          weight: 400
        - asset: assets/fonts/Sf-Pro/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: assets/fonts/Sf-Pro/SF-Pro-Display-MediumItalic.otf
          style: italic
          weight: 500
        - asset: assets/fonts/Sf-Pro/SF-Pro-Display-Semibold.otf
          weight: 600
        - asset: assets/fonts/Sf-Pro/SF-Pro-Display-SemiboldItalic.otf
          style: italic
          weight: 600
        - asset: assets/fonts/Sf-Pro/SF-Pro-Display-Bold.otf
          weight: 700
        - asset: assets/fonts/Sf-Pro/Sf-Pro-Display-BoldItalic.otf
          style: italic
          weight: 700
        - asset: assets/fonts/Sf-Pro/Sf-Pro-Display-Black.otf
          weight: 800
        - asset: assets/fonts/Sf-Pro/Sf-Pro-Display-BlackItalic.otf
          style: italic
          weight: 800
        - asset: assets/fonts/Sf-Pro/Sf-Pro-Display-Heavy.otf
          weight: 900
        - asset: assets/fonts/Sf-Pro/Sf-Pro-Display-HeavyItalic.otf
          style: italic
          weight: 900

flutter_gen:
  output: lib/core/gen/
  integrations:
    flutter_svg: true
    flare_flutter: false
    rive: true
    lottie: true

  assets:
    enabled: true
    outputs:
      package_parameter_enabled: true
      style: dot-delimiter
      class_name: RRJAssets
    exclude: [ ]

  fonts:
    enabled: true
    outputs:
      class_name: RRJFonts
