name: reservasi_rawat_jalan_mobile
description: Aplikasi Reservasi Rawat Jalan berbasis Mobile

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  dio: ^5.4.0
  intl: ^0.18.1
  lottie: ^3.0.0
  flutter_svg: ^2.0.9
  go_router: ^13.1.0
  easy_localization: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  flutter_gen_runner: ^5.4.0
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/raw/
    - assets/fonts/
    - assets/icons/
    - assets/langs/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Thin.ttf
          weight: 100
        - asset: assets/fonts/Lato-ThinItalic.ttf
          style: italic
          weight: 100
        - asset: assets/fonts/Lato-Light.ttf
          weight: 300
        - asset: assets/fonts/Lato-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/Lato-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lato-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/Lato-Black.ttf
          weight: 900
        - asset: assets/fonts/Lato-BlackItalic.ttf
          style: italic
          weight: 900

flutter_gen:
  output: lib/core/gen/
  integrations:
    flutter_svg: true
    flare_flutter: false
    rive: true
    lottie: true

  assets:
    enabled: true
    outputs:
      package_parameter_enabled: true
      style: dot-delimiter
      class_name: ReservasiRawatJalanAssets
    exclude: [ ]

  fonts:
    enabled: true
    outputs:
      class_name: ReservasiRawatJalanFonts