// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY_WEB'] ?? '',
    appId: '1:305882542351:web:01d3d469611cb5be944e7a',
    messagingSenderId: '305882542351',
    projectId: 'reservasi-rawat-jalan',
    authDomain: 'reservasi-rawat-jalan.firebaseapp.com',
    storageBucket: 'reservasi-rawat-jalan.appspot.com',
    measurementId: 'G-85MZSQYYW0',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY_ANDROID'] ?? '',
    appId: '1:305882542351:android:3d7de0e148d24c74944e7a',
    messagingSenderId: '305882542351',
    projectId: 'reservasi-rawat-jalan',
    storageBucket: 'reservasi-rawat-jalan.appspot.com',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY_IOS'] ?? '',
    appId: '1:305882542351:ios:0438aba18b1089c9944e7a',
    messagingSenderId: '305882542351',
    projectId: 'reservasi-rawat-jalan',
    storageBucket: 'reservasi-rawat-jalan.appspot.com',
    iosBundleId: 'com.ifkusyoba.reservasiRawatJalanMobile',
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY_MACOS'] ?? '',
    appId: '1:305882542351:ios:0438aba18b1089c9944e7a',
    messagingSenderId: '305882542351',
    projectId: 'reservasi-rawat-jalan',
    storageBucket: 'reservasi-rawat-jalan.appspot.com',
    iosBundleId: 'com.ifkusyoba.reservasiRawatJalanMobile',
  );

  static FirebaseOptions windows = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY_WINDOWS'] ?? '',
    appId: '1:305882542351:web:6cee0a21fe7072e0944e7a',
    messagingSenderId: '305882542351',
    projectId: 'reservasi-rawat-jalan',
    authDomain: 'reservasi-rawat-jalan.firebaseapp.com',
    storageBucket: 'reservasi-rawat-jalan.appspot.com',
    measurementId: 'G-FLJ8Y5JZW6',
  );
}
